//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppPatientBasicInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppPatientBasicInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Domain.Resources.AppPatientBasicInfo", typeof(AppPatientBasicInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string lblDOB {
            get {
                return ResourceManager.GetString("lblDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore name.
        /// </summary>
        public static string lblForeName {
            get {
                return ResourceManager.GetString("lblForeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gp code.
        /// </summary>
        public static string lblGpCode {
            get {
                return ResourceManager.GetString("lblGpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gp initials.
        /// </summary>
        public static string lblGpInitials {
            get {
                return ResourceManager.GetString("lblGpInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gp phone.
        /// </summary>
        public static string lblGpPhone {
            get {
                return ResourceManager.GetString("lblGpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur name.
        /// </summary>
        public static string lblGpSurName {
            get {
                return ResourceManager.GetString("lblGpSurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address #1.
        /// </summary>
        public static string lblNokAddress1 {
            get {
                return ResourceManager.GetString("lblNokAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address #2.
        /// </summary>
        public static string lblNokAddress2 {
            get {
                return ResourceManager.GetString("lblNokAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address #3.
        /// </summary>
        public static string lblNokAddress3 {
            get {
                return ResourceManager.GetString("lblNokAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address #4.
        /// </summary>
        public static string lblNokAddress4 {
            get {
                return ResourceManager.GetString("lblNokAddress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string lblNokCode {
            get {
                return ResourceManager.GetString("lblNokCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblNokName {
            get {
                return ResourceManager.GetString("lblNokName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string lblNokRelationship {
            get {
                return ResourceManager.GetString("lblNokRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number.
        /// </summary>
        public static string lblPasNumber {
            get {
                return ResourceManager.GetString("lblPasNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur name.
        /// </summary>
        public static string lblSurName {
            get {
                return ResourceManager.GetString("lblSurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home telephone number.
        /// </summary>
        public static string lblTel {
            get {
                return ResourceManager.GetString("lblTel", resourceCulture);
            }
        }
    }
}
