//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Domain.Resources.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string Backbtn {
            get {
                return ResourceManager.GetString("Backbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Closebtn {
            get {
                return ResourceManager.GetString("Closebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select --.
        /// </summary>
        public static string lblChoose {
            get {
                return ResourceManager.GetString("lblChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string lblFemale {
            get {
                return ResourceManager.GetString("lblFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string lblMale {
            get {
                return ResourceManager.GetString("lblMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Gp details.
        /// </summary>
        public static string NewGpDetails {
            get {
                return ResourceManager.GetString("NewGpDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Next Of Kin.
        /// </summary>
        public static string NewNextOfKin {
            get {
                return ResourceManager.GetString("NewNextOfKin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new patient basic info.
        /// </summary>
        public static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        public static string NewRecordbtn {
            get {
                return ResourceManager.GetString("NewRecordbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient {0} {1} details.
        /// </summary>
        public static string PatientInfoDetails {
            get {
                return ResourceManager.GetString("PatientInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Removebtn {
            get {
                return ResourceManager.GetString("Removebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to delete {0} {1} ?.
        /// </summary>
        public static string RemoveConfirmMessage {
            get {
                return ResourceManager.GetString("RemoveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string RemoveGpDetails {
            get {
                return ResourceManager.GetString("RemoveGpDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string RemoveNextOfKin {
            get {
                return ResourceManager.GetString("RemoveNextOfKin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete patient ( {0} {1} ).
        /// </summary>
        public static string RemovePatient {
            get {
                return ResourceManager.GetString("RemovePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Savebtn {
            get {
                return ResourceManager.GetString("Savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Gp details ( {0} ).
        /// </summary>
        public static string UpdateGpDetails {
            get {
                return ResourceManager.GetString("UpdateGpDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Next Of Kin ( {0} ).
        /// </summary>
        public static string UpdateNextOfKin {
            get {
                return ResourceManager.GetString("UpdateNextOfKin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update patient ( {0} {1} ).
        /// </summary>
        public static string UpdatePatient {
            get {
                return ResourceManager.GetString("UpdatePatient", resourceCulture);
            }
        }
    }
}
